export const mockdata = {
  status: "complete",
  customer_email: "mingmatenzing689@gmail.com",
  lineItems: {
    object: "list",
    data: [
      {
        id: "li_1ShDb2CxFgDb5bdNDCm2uCOq",
        object: "item",
        amount_discount: 0,
        amount_subtotal: 1450,
        amount_tax: 0,
        amount_total: 1450,
        currency: "aud",
        description: "Chicken Wings",
        metadata: {
          menuItemId: "df0cbe81-45cc-40ca-b204-2d6c2461bbd1",
          name: "Chicken Wings",
          specialInstructions: "extra spicy mayo",
        },
        price: {
          id: "price_1ShDb2CxFgDb5bdNMp1ZNpRr",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1766427160,
          currency: "aud",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_TeWeSCNJiQKRpa",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 1450,
          unit_amount_decimal: "1450",
        },
        quantity: 1,
      },
      {
        id: "li_1ShDb2CxFgDb5bdNKwWKnOej",
        object: "item",
        amount_discount: 0,
        amount_subtotal: 1350,
        amount_tax: 0,
        amount_total: 1350,
        currency: "aud",
        description: "Crispy Calamari",
        metadata: {
          menuItemId: "dd4d3bb4-cfdb-4d5c-80a6-4b98aa8c6bd4",
          name: "Crispy Calamari",
          specialInstructions: "",
        },
        price: {
          id: "price_1ShDb2CxFgDb5bdNImoKD3P8",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1766427160,
          currency: "aud",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_TeWeGGe4LATDir",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 1350,
          unit_amount_decimal: "1350",
        },
        quantity: 1,
      },
      {
        id: "li_1ShDb2CxFgDb5bdNSb8ujAT8",
        object: "item",
        amount_discount: 0,
        amount_subtotal: 650,
        amount_tax: 0,
        amount_total: 650,
        currency: "aud",
        description: "Garlic Bread",
        metadata: {
          menuItemId: "40aa84b7-3a94-478c-be05-e3701f029b33",
          name: "Garlic Bread",
          specialInstructions: "more toasted please",
        },
        price: {
          id: "price_1ShDb2CxFgDb5bdNVK3tqcpJ",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1766427160,
          currency: "aud",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_TeWeTWF8Zbcmjs",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 650,
          unit_amount_decimal: "650",
        },
        quantity: 1,
      },
    ],
    has_more: false,
    url: "/v1/checkout/sessions/cs_test_b1pXeupWUjlZ79rp4v3IWHPB5DB5U7v3LlrkoQyNo0i3ttq9qliJZH2Dpo/line_items",
  },
  table: {
    table_id: "9e6d7f54-65d8-4f6a-a1b6-5a7f1cb86018",
  },
  metadata: {
    menuItemId: "df0cbe81-45cc-40ca-b204-2d6c2461bbd1",
    name: "Chicken Wings",
    specialInstructions: "extra spicy mayo",
  },
};
